export const categoryExplanations: { [key: string]: string } = {
    'Income Tax': 'This is the tax on your earnings paid to the federal government. The rate depends on your income level and tax class.',
    'Solidarity Surcharge': 'A small additional tax on top of your income tax, originally for German reunification costs. It\'s being phased out for most earners but may still apply to higher incomes.',
    'Church Tax': 'A tax paid by members of officially recognized churches in Germany. If you are not registered as a member of a church, this should be zero.',
    'Pension Insurance': 'Your mandatory contribution to the state pension system (Rentenversicherung). This funds your state pension when you retire.',
    'Health Insurance': 'Your mandatory contribution to the state health insurance system (gesetzliche Krankenversicherung - GKV). This covers your medical costs.',
    'Nursing Care Insurance': 'Your contribution to the long-term care insurance (Pflegeversicherung), which covers costs if you need nursing assistance later in life.',
    'Unemployment Insurance': 'Your contribution to the unemployment insurance system (Arbeitslosenversicherung). This provides you with unemployment benefits if you lose your job.',
    'Employer Pension Contribution': 'This is the amount your employer contributes to your state pension on your behalf. It does not come out of your gross salary.',

    'Gross Income': 'Your total gross earnings including salary and any taxable benefits in kind (Sachbezüge).',
    'Pension Payments (Versorgungsbezüge)': 'Payments from former employers or pension institutions, usually after retirement. These may be partially or fully taxable.',
    'Substitute Wage Payments (Lohnersatzleistungen)': 'Payments such as unemployment benefits, sick pay, or parental allowance, which are not taxed directly but can affect your tax rate.',
    'Tax-Free Income under Double Taxation Agreement': 'Income earned abroad that is exempt from German taxes due to a double taxation treaty.',
    'Tax-Free Employer Contributions for Commuting': 'Employer-paid subsidies for commuting costs that are tax-free up to a certain amount.',
    'Flat-Taxed Commuting Benefits (15%)': 'Employer commuting subsidies that are taxed at a flat rate of 15%.',
    'Tax-Free Meal Allowance': 'Meal subsidies from your employer while you are working away from your usual place of work. These are tax-free within certain limits.',
    'Tax-Free Employer Contributions for Double Households': 'Tax-free support from your employer if you maintain a second household due to work.',
    'Employer Subsidy to Public Health Insurance': 'Your employer\'s share of contributions to the statutory health insurance system.',
    'Employer Subsidy to Private Health Insurance': 'Your employer\'s share of contributions to private health insurance, if applicable.',
    'Employer Subsidy to Long-Term Care Insurance': 'Your employer\'s share of long-term care insurance contributions.',
    'Employee Contribution to Public Health Insurance': 'Your share of the statutory health insurance contribution deducted from your gross salary.',
    'Employee Contribution to Nursing Care Insurance': 'Your share of contributions to the long-term care insurance system.',
    'Employee Contribution to Unemployment Insurance': 'Your share of the unemployment insurance contribution deducted from your salary.',
    'Private Health and Nursing Insurance': 'Your full contributions to private health and/or nursing insurance, if applicable.',
    'DBA Turkey Exemption': 'A tax-free amount granted under the Double Taxation Agreement with Turkey.',
    'Multi-Year Pension or Severance Pay': 'Lump sum or back pay for multiple years, often including severance or pension payouts. These have special tax treatments.',
    'Death Benefits / Capital Payments / Pension Back Payments': 'One-time payments such as death benefits, capital disbursements or retroactive pension payments, which may be partially taxable.',
};
